version: "3.9"

services:

  database:
    image: postgres:13.6-alpine
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups

  backend:
    # ATENÇÃO: Substitua a imagem pela versão desejada
    image: linea/pzserver:backend_<VERSION>
    command: ./entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./archive/data:/archive/data
      - ./archive/django_static:/archive/django_static
    depends_on:
      - database

  frontend:
    # ATENÇÃO: Substitua a imagem pela versão desejada
    image: linea/pzserver:frontend_<VERSION>
    volumes:
      - ./.env.local:/app/.env.local

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      # ATENÇÃO: Altere a porta para uma porta compativel com o ambiente.
      - <PORT>:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./archive/django_static:/var/www/django_static
      - ./archive/data:/var/www/data
    depends_on:
      - backend
      - frontend
