from types import SimpleNamespace
from unittest import mock

from core.models import Pipeline, Process, Product, ProductStatus, ProductType, Release
from core.process.builders.upload_builder import UploadBuilder
from core.process.service import ProcessService
from django.contrib.auth.models import User
from django.test import TestCase, override_settings


class UploadBuilderTestCase(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            "john", "john@snow.com", "you_know_nothing"
        )
        self.product_type = ProductType.objects.create(
            name="validation_results",
            display_name="Validation Results",
        )
        self.pipeline = Pipeline.objects.create(
            name="combine_redshift_dedup",
            display_name="Combine Redshift Dedup",
            version="1.0.0",
            output_product_type=self.product_type,
        )

    def test_build_sets_upload_status_to_processing(self):
        serializer = SimpleNamespace(
            initial_data={
                "pipeline": self.pipeline.pk,
                "display_name": "Combined Catalog",
                "description": "Generated by process",
            }
        )

        product = UploadBuilder(serializer, self.user).build()

        self.assertEqual(ProductStatus.PROCESSING, product.status)
        self.assertIsNotNone(product.path)


class ProcessServiceTestCase(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            "john", "john@snow.com", "you_know_nothing"
        )
        self.product_type = ProductType.objects.create(
            name="redshift_catalog",
            display_name="Redshift Catalog",
        )
        self.pipeline = Pipeline.objects.create(
            name="combine_redshift_dedup",
            display_name="Combine Redshift Dedup",
            version="1.0.0",
            output_product_type=self.product_type,
        )
        self.upload = Product.objects.create(
            product_type=self.product_type,
            user=self.user,
            display_name="Combined Catalog",
            internal_name="1_combined_catalog",
            path="redshift_catalog/1_combined_catalog",
            status=ProductStatus.PROCESSING,
        )
        self.process = Process.objects.create(
            display_name="Combined Catalog",
            pipeline=self.pipeline,
            upload=self.upload,
            user=self.user,
        )

    @mock.patch("core.process.service.InputsBuilder.build", return_value=[])
    @mock.patch("core.process.service.BasePipelineHandler.get_handler")
    @mock.patch("core.process.service.Maestro")
    def test_submit_accepts_dict_used_config(
        self,
        maestro_cls,
        get_handler,
        _build_inputs,
    ):
        class FakeHandler:
            def __init__(self, request, process):
                self.request = request
                self.process = process

            def build_config(self):
                return {"param": {"debug": True}}

        get_handler.return_value = FakeHandler

        maestro = maestro_cls.return_value
        maestro.start.return_value = {
            "id": 123,
            "path_str": "combine_redshift_dedup/00000123",
            "used_config": {
                "param": {"debug": True},
                "inputs": {"specz": []},
                "output_dir": self.upload.path,
            },
        }

        request = SimpleNamespace(data={})

        ProcessService(request, self.process).submit()
        self.process.refresh_from_db()

        self.assertEqual(123, self.process.orchestration_process_id)
        self.assertEqual("combine_redshift_dedup/00000123", self.process.path)
        self.assertEqual(
            {
                "param": {"debug": True},
                "inputs": {"specz": []},
                "output_dir": self.upload.path,
            },
            self.process.used_config,
        )

    @override_settings(
        DATASETS_DIR="/datasets",
        ORCHEST_URL="http://orchestrator",
        UPLOAD_DIR="/uploads",
    )
    @mock.patch("core.process.service.InputsBuilder.build", return_value=[])
    @mock.patch("core.process.pipelines.training_set_maker.Maestro")
    @mock.patch("core.process.service.Maestro")
    def test_submit_training_set_maker_sends_hydrated_hats_config(
        self,
        service_maestro_cls,
        handler_maestro_cls,
        _build_inputs,
    ):
        self.pipeline.name = "training_set_maker"
        self.pipeline.save(update_fields=["name"])
        release = Release.objects.create(
            name="dp1",
            display_name="DP1",
            indexing_column="objectId",
        )
        self.process.release = release
        self.process.used_config = {
            "param": {
                "flux_type": "cmodel",
                "dereddening": "planck",
                "convert_flux_to_mag": True,
                "hats_config": {
                    "input": {
                        "catalog_folder": "/tmp/forbidden",
                        "compute_magnitude": False,
                    },
                    "dust": {
                        "path_to_dustmaps": "/tmp/forbidden",
                        "use_dustmap": "planck",
                    },
                },
            }
        }
        self.process.save(update_fields=["release", "used_config"])

        handler_maestro_cls.return_value.hats_config.return_value = {
            "config": {
                "input": {
                    "catalog_folder": "/datasets/dp1/catalogs/object",
                    "compute_magnitude": True,
                },
                "dust": {
                    "path_to_dustmaps": "/datasets/dustmaps",
                    "use_dustmap": "sfd",
                },
                "cluster": {"executor": "slurm"},
            }
        }

        service_maestro = service_maestro_cls.return_value

        def start_process(*, pipeline, config):
            return {
                "id": 321,
                "path_str": "training_set_maker/00000321",
                "used_config": config,
            }

        service_maestro.start.side_effect = start_process
        request = SimpleNamespace(data={"output_format": "hats"})

        with self.assertLogs("core.services.hats_config", level="WARNING"):
            ProcessService(request, self.process).submit()

        service_maestro.start.assert_called_once()
        submitted_config = service_maestro.start.call_args.kwargs["config"]
        self.assertEqual(
            "/datasets/dp1",
            submitted_config["inputs"]["dataset"]["path"],
        )
        self.assertEqual(
            {"id": "objectId"},
            submitted_config["inputs"]["dataset"]["columns"],
        )
        self.assertEqual([], submitted_config["inputs"]["specz"])
        self.assertEqual("hats", submitted_config["output_format"])

        hats_config = submitted_config["param"]["hats_config"]
        self.assertEqual(
            "/datasets/dp1/catalogs/object",
            hats_config["input"]["catalog_folder"],
        )
        self.assertFalse(hats_config["input"]["compute_magnitude"])
        self.assertEqual(
            "/datasets/dustmaps",
            hats_config["dust"]["path_to_dustmaps"],
        )
        self.assertEqual("planck", hats_config["dust"]["use_dustmap"])
        self.assertEqual({"executor": "slurm"}, hats_config["cluster"])

        self.process.refresh_from_db()
        self.assertEqual(321, self.process.orchestration_process_id)
        self.assertEqual(hats_config, self.process.used_config["param"]["hats_config"])

    @mock.patch("core.process.service.Maestro")
    @mock.patch("core.process.service.BasePipelineHandler.get_handler")
    def test_submit_logs_stage_on_failure(
        self,
        get_handler,
        _maestro_cls,
    ):
        get_handler.side_effect = ValueError("handler missing")
        request = SimpleNamespace(data={})

        with self.assertLogs("django", level="ERROR") as captured_logs:
            with self.assertRaisesRegex(ValueError, "handler missing"):
                ProcessService(request, self.process).submit()

        self.assertEqual("resolve_handler", self.process._submission_stage)
        joined_logs = "\n".join(captured_logs.output)
        self.assertIn("Process submission stage failed", joined_logs)
        self.assertIn("stage=resolve_handler", joined_logs)
        self.assertIn(f"process_id={self.process.pk}", joined_logs)
