from types import SimpleNamespace
from unittest import mock

from core.models import Pipeline, Process, Product, ProductStatus, ProductType
from core.process.builders.upload_builder import UploadBuilder
from core.process.service import ProcessService
from django.contrib.auth.models import User
from django.test import TestCase


class UploadBuilderTestCase(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            "john", "john@snow.com", "you_know_nothing"
        )
        self.product_type = ProductType.objects.create(
            name="validation_results",
            display_name="Validation Results",
        )
        self.pipeline = Pipeline.objects.create(
            name="combine_redshift_dedup",
            display_name="Combine Redshift Dedup",
            version="1.0.0",
            output_product_type=self.product_type,
        )

    def test_build_sets_upload_status_to_processing(self):
        serializer = SimpleNamespace(
            initial_data={
                "pipeline": self.pipeline.pk,
                "display_name": "Combined Catalog",
                "description": "Generated by process",
            }
        )

        product = UploadBuilder(serializer, self.user).build()

        self.assertEqual(ProductStatus.PROCESSING, product.status)
        self.assertIsNotNone(product.path)


class ProcessServiceTestCase(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            "john", "john@snow.com", "you_know_nothing"
        )
        self.product_type = ProductType.objects.create(
            name="redshift_catalog",
            display_name="Redshift Catalog",
        )
        self.pipeline = Pipeline.objects.create(
            name="combine_redshift_dedup",
            display_name="Combine Redshift Dedup",
            version="1.0.0",
            output_product_type=self.product_type,
        )
        self.upload = Product.objects.create(
            product_type=self.product_type,
            user=self.user,
            display_name="Combined Catalog",
            internal_name="1_combined_catalog",
            path="redshift_catalog/1_combined_catalog",
            status=ProductStatus.PROCESSING,
        )
        self.process = Process.objects.create(
            display_name="Combined Catalog",
            pipeline=self.pipeline,
            upload=self.upload,
            user=self.user,
        )

    @mock.patch("core.process.service.InputsBuilder.build", return_value=[])
    @mock.patch("core.process.service.BasePipelineHandler.get_handler")
    @mock.patch("core.process.service.Maestro")
    def test_submit_accepts_dict_used_config(
        self,
        maestro_cls,
        get_handler,
        _build_inputs,
    ):
        class FakeHandler:
            def __init__(self, request, process):
                self.request = request
                self.process = process

            def build_config(self):
                return {"param": {"debug": True}}

        get_handler.return_value = FakeHandler

        maestro = maestro_cls.return_value
        maestro.start.return_value = {
            "id": 123,
            "path_str": "combine_redshift_dedup/00000123",
            "used_config": {
                "param": {"debug": True},
                "inputs": {"specz": []},
                "output_dir": self.upload.path,
            },
        }

        request = SimpleNamespace(data={})

        ProcessService(request, self.process).submit()
        self.process.refresh_from_db()

        self.assertEqual(123, self.process.orchestration_process_id)
        self.assertEqual("combine_redshift_dedup/00000123", self.process.path)
        self.assertEqual(
            {
                "param": {"debug": True},
                "inputs": {"specz": []},
                "output_dir": self.upload.path,
            },
            self.process.used_config,
        )
