# Generated by Django 4.0.2 on 2022-03-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_release_product_description_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_dir',
        ),
    ]
