from core.views.release import ReleaseViewSet
from core.views.product_type import ProductTypeViewSet
from core.views.product import ProductViewSet
from core.views.product_content import ProductContentViewSet
from core.views.product_file import ProductFileViewSet
from core.views.user import LoggedUserView
from core.views.user import GetToken
from core.views.user import CsrfToOauth
from core.views.user import Logout
from core.views.user import UserViewSet
