version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      # dockerfile: backend/Dockerfile
    volumes:
      - ..:/workspaces:cached
      - ./archive/log/backend:/archive/log:cached
      - ./archive/data:/archive/data:cached
      - ./orchestration/pipelines:/pipelines:cached
      - ./orchestration/processes:/processes:cached
      - ./orchestration/datasets:/datasets:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    env_file:
      - .env
