# Generated by Django 4.0.2 on 2023-06-28 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pipeline_name', models.CharField(max_length=255)),
                ('pipeline_version', models.CharField(max_length=255)),
                ('pipeline_config', models.JSONField()),
                ('used_config', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stoped_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Successful'), (1, 'Pending'), (2, 'Running'), (3, 'Revoked'), (4, 'Failed')], default=1, verbose_name='Status')),
                ('path', models.FilePathField(blank=True, default=None, null=True, verbose_name='Path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
