# Generated by Django 4.0.2 on 2023-06-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='stoped_at',
            new_name='ended_at',
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='pipeline_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='pipeline_version',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='task_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
