# Generated by Django 4.0.2 on 2023-06-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_product_survey'),
        ('orchestration', '0002_rename_stoped_at_process_ended_at_alter_process_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='process',
            name='name',
        ),
        migrations.RemoveField(
            model_name='process',
            name='pipeline_config',
        ),
        migrations.RemoveField(
            model_name='process',
            name='pipeline_name',
        ),
        migrations.AddField(
            model_name='process',
            name='inputs',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='processes', to='core.Product'),
        ),
        migrations.AddField(
            model_name='process',
            name='release',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.release'),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_release', models.BooleanField(default=False)),
                ('product_types', models.ManyToManyField(blank=True, default=None, null=True, related_name='pipelines', to='core.ProductType')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='pipeline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='orchestration.pipeline'),
            preserve_default=False,
        ),
    ]
