# Generated by Django 4.0.2 on 2023-06-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0003_rename_description_process_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='config',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='version',
        ),
    ]
