# Generated by Django 4.0.2 on 2023-06-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_product_survey'),
        ('orchestration', '0004_remove_pipeline_config_remove_pipeline_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='product_types',
            field=models.ManyToManyField(related_name='pipelines', to='core.ProductType'),
        ),
        migrations.AlterField(
            model_name='process',
            name='inputs',
            field=models.ManyToManyField(related_name='processes', to='core.Product'),
        ),
    ]
