# Generated by Django 4.0.2 on 2022-04-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_product_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
