# Generated by Django 4.0.2 on 2022-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_file_extension_alter_product_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
