# Generated by Django 4.0.2 on 2022-06-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.release'),
        ),
    ]
