# Generated by Django 4.0.2 on 2022-07-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_product_type_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='Order of columns in the product.', null=True, verbose_name='Order'),
        ),
    ]
