# Generated by Django 4.0.2 on 2022-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_product_description_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Registering'), (1, 'Registered'), (2, 'Published')], default=0, verbose_name='Status'),
        ),
    ]
