# Generated by Django 4.0.2 on 2022-07-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_productcontent_product_productfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Main'), (1, 'Description'), (2, 'Auxiliary')], default=0, verbose_name='Status'),
        ),
    ]
