# Generated by Django 4.0.2 on 2022-07-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_productfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productfile',
            name='filename',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productfile',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
