# Generated by Django 4.0.2 on 2022-07-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_productfile_extension_productfile_filename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfile',
            old_name='filename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='productfile',
            name='type',
        ),
    ]
