# Generated by Django 4.0.2 on 2022-07-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_filename_productfile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='roles',
            field=models.IntegerField(choices=[(0, 'Main'), (1, 'Description'), (2, 'Auxiliary')], default=0, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='productfile',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mime Type'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
