# Generated by Django 4.0.2 on 2022-07-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productfile_roles_productfile_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfile',
            old_name='roles',
            new_name='role',
        ),
    ]
