# Generated by Django 4.0.2 on 2022-08-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file_size',
        ),
    ]
