# Generated by Django 4.0.2 on 2022-08-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_product_file_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.FilePathField(blank=True, default=None, null=True, verbose_name='Path'),
        ),
    ]
