# Generated by Django 4.0.2 on 2022-10-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="attributes",
        ),
        migrations.AddField(
            model_name="producttype",
            name="description",
            field=models.TextField(default=None, blank=True, null=True),
            preserve_default=False,
        ),
    ]
