# Generated by Django 4.0.2 on 2022-10-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_producttype_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
