# Generated by Django 4.0.2 on 2023-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_product_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='alias',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Alias'),
        ),
    ]
