# Generated by Django 5.0.6 on 2024-05-28 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_version', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('used_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=55)),
                ('path', models.FilePathField(blank=True, default=None, null=True, verbose_name='Path')),
                ('comment', models.TextField(blank=True, null=True)),
                ('inputs', models.ManyToManyField(related_name='processes', to='core.product')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.pipeline')),
                ('release', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.release')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
