# Generated by Django 5.0.6 on 2024-05-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pipeline_product_types_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='core.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='inputs',
            field=models.ManyToManyField(related_name='inputs', to='core.product'),
        ),
    ]
