# Generated by Django 5.0.6 on 2024-05-29 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_process_upload_alter_process_inputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='core.product'),
        ),
    ]
