# Generated by Django 5.0.6 on 2024-05-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_process_upload_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='upload_product_type',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='output_product_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='output_product_type', to='core.producttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='display_name',
            field=models.CharField(default='Test DN', max_length=255),
            preserve_default=False,
        ),
    ]
