# Generated by Django 5.0.6 on 2024-06-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_process_orchestration_process_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='orchestration_process_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
