# Generated by Django 5.0.6 on 2024-08-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_process_path_alter_release_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='indexing_column',
            field=models.CharField(default='id', max_length=255),
            preserve_default=False,
        ),
    ]
