# Generated by Django 5.1.1 on 2024-12-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_release_indexing_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
