# Generated by Django 5.1.1 on 2024-12-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_producttype_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfile",
            name="n_rows",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of rows"
            ),
        ),
    ]
