# Generated by Django 5.1.1 on 2025-01-23 18:51

import core.models.product_file
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.product_file.upload_product_files,
            ),
        ),
    ]
