# Generated by Django 5.1.1 on 2025-01-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_alter_productfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Registering"),
                    (1, "Published"),
                    (2, "Deleted"),
                    (3, "Processing"),
                    (9, "Failed"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
