# Generated by Django 5.1.1 on 2025-02-19 14:33

import core.models.product_file
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=core.models.product_file.upload_product_files,
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Name"
            ),
        ),
    ]
