# Generated by Django 5.1.1 on 2025-06-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_productfile_file_alter_productfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
