# Generated by Django 5.1.1 on 2025-08-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_product_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='core.product'),
        ),
    ]
