# Generated by Django 5.1.1 on 2025-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_process_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='dereddening',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='fluxes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='has_flux_hats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='release',
            name='has_mag_hats',
            field=models.BooleanField(default=False),
        ),
    ]
