# Generated by Django 5.1.1 on 2025-09-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_release_dereddening_release_fluxes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do grupo conforme recebido do SAML IdP', max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Nome amigável para exibição', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descrição do grupo de acesso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se falso, o grupo não terá nenhum acesso')),
            ],
            options={
                'verbose_name': 'Access Group',
                'verbose_name_plural': 'Access Groups',
            },
        ),
        migrations.AddField(
            model_name='release',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o release é acessível a todos os usuários autenticados, independente dos grupos'),
        ),
        migrations.AddField(
            model_name='release',
            name='access_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos que têm acesso a este release. Se vazio, todos os usuários autenticados têm acesso.', related_name='accessible_releases', to='core.accessgroup'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Última vez que o usuário foi visto com este grupo no SAML')),
                ('is_active', models.BooleanField(default=True, help_text='Se falso, a associação está desabilitada')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.accessgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
