# Generated by Django 5.1.1 on 2025-09-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0049_accessgroup_release_is_public_release_access_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='access_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos que têm acesso a este release. Se vazio, todos os usuários autenticados têm acesso.', related_name='accessible_releases', to='auth.group'),
        ),
        migrations.CreateModel(
            name='GroupMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('local', 'Local'), ('saml', 'SAML')], default='local', help_text='Origem do grupo', max_length=10)),
                ('display_name', models.CharField(blank=True, help_text='Nome amigável para exibição', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descrição do grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se falso, o grupo não será considerado para controle de acesso')),
                ('last_saml_sync', models.DateTimeField(blank=True, help_text='Última sincronização via SAML (apenas para grupos SAML)', null=True)),
                ('group', models.OneToOneField(help_text='Grupo Django associado', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Metadata',
                'verbose_name_plural': 'Group Metadata',
            },
        ),
        migrations.CreateModel(
            name='SAMLGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Última vez que o usuário foi visto com este grupo no SAML')),
                ('is_active', models.BooleanField(default=True, help_text='Se falso, a associação foi desativada (grupo não presente no SAML atual)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saml_memberships', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saml_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SAML Group Membership',
                'verbose_name_plural': 'SAML Group Memberships',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
