# Generated by Django 5.1.1 on 2025-09-19 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0050_alter_release_access_groups_groupmetadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_memberships', to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='samlgroupmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='samlgroupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='samlgroupmembership',
            name='user',
        ),
        migrations.RenameField(
            model_name='groupmembership',
            old_name='created_at',
            new_name='first_seen',
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se falso, a associação foi desativada (grupo não presente no SAML atual)'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccessGroup',
        ),
        migrations.DeleteModel(
            name='SAMLGroupMembership',
        ),
    ]
