# Generated by Django manually

from django.db import migrations


def migrate_saml_to_linea(apps, schema_editor):
    """
    Converte todos os registros com source='saml' para source='linea'
    """
    GroupMetadata = apps.get_model('core', 'GroupMetadata')
    
    # Atualizar todos os registros com source 'saml' para 'linea'
    updated_count = GroupMetadata.objects.filter(source='saml').update(source='linea')
    
    if updated_count > 0:
        print(f"Convertidos {updated_count} registros de source 'saml' para 'linea'")


def reverse_migrate_linea_to_saml(apps, schema_editor):
    """
    Reverte a conversão de 'linea' para 'saml' (para rollback)
    """
    GroupMetadata = apps.get_model('core', 'GroupMetadata')
    
    # Reverter todos os registros com source 'linea' para 'saml'
    reverted_count = GroupMetadata.objects.filter(source='linea').update(source='saml')
    
    if reverted_count > 0:
        print(f"Revertidos {reverted_count} registros de source 'linea' para 'saml'")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_rename_samlgroupmembership_to_groupmembership'),
    ]

    operations = [
        migrations.RunPython(
            migrate_saml_to_linea,
            reverse_migrate_linea_to_saml,
        ),
    ]