# Generated by Django manually

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_migrate_saml_to_linea_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmetadata',
            old_name='last_saml_sync',
            new_name='last_sync',
        ),
    ]