# Generated by Django 5.1.1 on 2025-09-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_rename_last_saml_sync_groupmetadata_last_sync'),
    ]

    operations = [
        # Remove is_active field from GroupMetadata
        migrations.RemoveField(
            model_name='groupmetadata',
            name='is_active',
        ),
        # Remove is_active field from GroupMembership
        migrations.RemoveField(
            model_name='groupmembership',
            name='is_active',
        ),
    ]
