# Generated by Django 5.1.1 on 2025-09-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0054_auto_20250925_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last time the user was seen with this group in the IdP'),
        ),
        migrations.AlterField(
            model_name='groupmetadata',
            name='description',
            field=models.TextField(blank=True, help_text='Group description'),
        ),
        migrations.AlterField(
            model_name='groupmetadata',
            name='display_name',
            field=models.CharField(blank=True, help_text='Friendly name for display', max_length=255),
        ),
        migrations.AlterField(
            model_name='groupmetadata',
            name='group',
            field=models.OneToOneField(help_text='Associated Django group', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='groupmetadata',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Last synchronization via IdP (only for Linea groups)', null=True),
        ),
        migrations.AlterField(
            model_name='groupmetadata',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('linea', 'LIneA')], default='local', help_text='Group origin', max_length=10),
        ),
        migrations.AlterField(
            model_name='release',
            name='access_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that have access to this release. If empty, all authenticated users have access.', related_name='accessible_releases', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='release',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, the release is accessible to all authenticated users, regardless of groups'),
        ),
    ]
