# Generated by Django 5.1.1 on 2025-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_is_linea_managed_consolidate_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
