# Generated by Django 5.1.1 on 2026-05-06 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_delete_groupmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDownloadArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "archive_path",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("filename", models.CharField(max_length=255)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                ("source_signature", models.CharField(max_length=64)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_download_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_archives",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "status"],
                        name="core_produc_product_03ac77_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_produc_expires_c15c23_idx"
                    ),
                    models.Index(
                        fields=["source_signature"],
                        name="core_produc_source__f3b8e2_idx",
                    ),
                ],
            },
        ),
    ]
