# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_delete_groupmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfile",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productfile",
            name="storage_kind",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("hats_collection", "HATS Collection"),
                ],
                default="file",
                max_length=32,
                verbose_name="Storage Kind",
            ),
        ),
    ]
