name: Test API workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.10'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"    
    - name: Install requirements
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#     - name: Run tests and collect coverage
#       working-directory: ./backend
#       run: pytest --cov .
    - name: Run tests and collect coverage
      working-directory: ./backend    
      run: pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
#     - name: Upload coverage reports to Codecov
#       working-directory: ./backend
#       run: |
#         # Replace `linux` below with the appropriate OS
#         # Options are `alpine`, `linux`, `macos`, `windows`
#         curl -Os https://uploader.codecov.io/latest/linux/codecov
#         chmod +x codecov
#         ./codecov -t ${CODECOV_TOKEN}
